server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: standing-order-service
              uri: lb://standing-order-service
              predicates:
                - Path=/standing-orders, /standing-orders/**
            - id: execution-service
              uri: lb://execution-service
              predicates:
                - Path=/executions, /executions/**
            - id: payment-service-transfers
              uri: lb://payment-service
              predicates:
                - Path=/transfers, /transfers/**
            - id: payment-service-accounts
              uri: lb://payment-service
              predicates:
                - Path=/accounts, /accounts/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notifications, /notifications/**
